# Generated by Django 2.1.5 on 2019-01-10 11:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.CharField(max_length=255, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChatLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_logs', to='bottieverse.Bot')),
            ],
        ),
        migrations.CreateModel(
            name='Intent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('agent', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bottieverse.Bot')),
            ],
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required', models.BooleanField()),
                ('name', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('entities', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bottieverse.Bot')),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(max_length=255)),
                ('intent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response', to='bottieverse.Intent')),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('unique_identifier', models.CharField(max_length=255, unique=True)),
                ('secret_key', models.CharField(max_length=255, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingPhrase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase', models.CharField(max_length=255)),
                ('intent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_phrase', to='bottieverse.Intent')),
            ],
        ),
        migrations.AddField(
            model_name='chatlog',
            name='response',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bottieverse.Response'),
        ),
        migrations.AddField(
            model_name='bot',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bots', to='bottieverse.Tenant'),
        ),
        migrations.AddField(
            model_name='action',
            name='intent',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bottieverse.Intent'),
        ),
        migrations.AddField(
            model_name='action',
            name='parameters',
            field=models.ManyToManyField(to='bottieverse.Parameter'),
        ),
    ]
