# Generated by Django 2.1.2 on 2018-10-15 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bottieverse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bottieverse.Bot')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bottieverse.BotResponse')),
            ],
        ),
    ]
