# Generated by Django 2.1.2 on 2018-10-15 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bottieverse', '0003_auto_20181015_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='botresponse',
            name='welcome_message',
            field=models.BooleanField(default=False),
        ),
    ]
